describe("ftdetect", function()
	local dir
	before_each(function()
		dir = vim.fn.tempname()
		vim.fn.mkdir(dir .. "/proj/classes", "p")
		vim.fn.mkdir(dir .. "/other", "p")
		vim.fn.writefile({ "{}" }, dir .. "/proj/sfdx-project.json")
		vim.cmd("runtime! ftdetect/sf-nvim.lua")
	end)
	after_each(function()
		vim.fn.delete(dir, "rf")
	end)

	it("claims .cls/.trigger only inside an SFDX project", function()
		assert.equals("apex", vim.filetype.match({ filename = dir .. "/proj/classes/A.cls" }))
		assert.equals("apex", vim.filetype.match({ filename = dir .. "/proj/classes/A.trigger" }))
		assert.not_equals("apex", vim.filetype.match({ filename = dir .. "/other/A.cls" }) or "")
	end)

	it("always claims .soql/.apex/.apexlog", function()
		assert.equals("soql", vim.filetype.match({ filename = dir .. "/other/q.soql" }))
		assert.equals("apex", vim.filetype.match({ filename = dir .. "/other/s.apex" }))
		assert.equals("apexlog", vim.filetype.match({ filename = dir .. "/other/x.apexlog" }))
	end)
end)
